
/*============================================================================
Filename : TOUCH_API.H
Project : QTouch Modular Library
Purpose : configuation macros for touch library

This file is part of QTouch Modular Library Release 5.1 example application.

Important Note: Do not edit this file manually.
                Use QTouch Configurator within Atmel Start to apply any
                modifications to this file.

Usage License: Refer license.h file for license information
Support: Visit http://www.microchip.com/support/hottopics.aspx
               to create MySupport case.

------------------------------------------------------------------------------
Copyright (c) 2017 Microchip. All rights reserved.
------------------------------------------------------------------------------
============================================================================*/

#ifndef TOUCH_API_H
#define TOUCH_API_H

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

    /*----------------------------------------------------------------------------
     *     include files
     *----------------------------------------------------------------------------*/
#include <xc.h>
#include "include/qtm_acq_cvd_dspic33ck_api.h"
#include "include/qtm_touch_key_0x0002_api.h"
#include "include/qtm_freq_hop_auto_0x0004_api.h"
#include "include/qtm_scroller_0x000b_api.h"
#include "../system/clock.h"


    void touch_init(void);
    void touch_process(void);
    void touch_timer_handler(void);

    uint16_t get_sensor_node_signal(uint16_t sensor_node);
    uint16_t get_sensor_node_reference(uint16_t sensor_node);
    uint16_t get_sensor_cc_val(uint16_t sensor_node);
    uint8_t get_sensor_state(uint16_t sensor_node);
    uint8_t get_sensor_threshold(uint16_t sensor_node);
    uint8_t get_current_frequency(void);
    uint8_t get_filter_frequency(uint8_t idx);
	uint8_t  get_scroller_state(uint16_t sensor_node);
	uint16_t get_scroller_position(uint16_t sensor_node);

#ifdef __cplusplus
}
#endif // __cplusplus
#endif // TOUCH_API_H
